<?php
/**
 * @file
 * Code for the luggage_bean_hero_ex feature.
 */

include_once 'luggage_bean_hero_ex.features.inc';

/**
 * Implements hook_theme().
 */
function luggage_bean_hero_ex_theme($existing, $type, $theme, $path) {
  $themes['bean__hero_ex'] = array(
    'template' => 'bean--hero-ex',
    'path' => drupal_get_path('module', 'luggage_bean_hero_ex') . '/templates'
  );

  return $themes;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function luggage_bean_hero_ex_form_bean_form_alter(&$form, &$form_state, $form_id) {
  if($form['#bundle'] == "hero_ex") {
    // Hide default bean type field since it's confusing and editor won't change it.
    $form['view_mode'] = array(
      '#type' => 'hidden',
    );
    //Add better description to label
    $form['label']['#description'] = t('This text will be used to name your hero. Users of your site will not see this.');
    //Add better description to title
    $form['title']['#description'] = t('The main title of your card. Additional content can be added below.');
  }
}

/*
 * Implements hook_preprocess_html.
 */
function luggage_bean_hero_ex_preprocess_html(&$vars) {
  // Override suitcase_interim styles for this site.
  global $theme;
  if ($theme == 'suitcase_interim') {
    drupal_add_css(drupal_get_path('module', 'luggage_bean_hero_ex') . '/css/luggage_bean_hero_ex.css', array('group' => 200));
  }
}